### ISSUE TITLE
Backdrop and ESC to Close

### ISSUE THREAD

**Issue by brigand** [howtomakeaturn/React-Lightbox#4]
Usually you can close a lightbox by clicking the X, clicking the backdrop, or pressing <kbd>esc</kbd>.  These could be configurable via props, but the default should be on for all of them.

**Comment by howtomakeaturn** [comment]
Nice suggestion...!
Thanks for your feedback! I'll add them later :)))

**Comment by howtomakeaturn** [comment]
Done. 

https://github.com/howtomakeaturn/React-Lightbox/commit/0a93ed93d3d87cd2b782d2e261eca34ceb6c53e1
